function cube = create_cube( min_point, side_lengths, name )

test22();

assert( nargin == 3 );

assert( isnumeric( min_point ) );
assert( isvector( min_point ) );
assert( numel( min_point ) == 3 );
assert( all( isfinite( min_point ) ) );

assert( isnumeric( side_lengths ) );
assert( isvector( side_lengths ) );
assert( numel( side_lengths ) == 3 );
assert( all( isfinite( side_lengths ) ) );
assert( all( 0.0 < side_lengths ) );

fv.vertices = [ ...
    0 0 0; ...
    1 0 0; ...
    1 1 0; ...
    0 1 0; ...
    0 1 1; ...
    0 0 1; ...
    1 0 1; ...
    1 1 1 ...
    ];
fv.vertices = fv.vertices .* side_lengths;
fv.vertices = fv.vertices + min_point;

fv.faces = [ ...
    1 3 2; ...
    1 4 3; ...
    1 5 4; ...
    1 6 5; ...
    1 2 7; ...
    1 7 6; ...
    5 6 7; ...
    5 7 8; ...
    2 3 7; ...
    3 8 7; ...
    3 4 5; ...
    3 5 8 ...
    ];

cube = geometry.Component( fv, name );

end

