% modified from
% user Sven
% originally posted 29 Aug 2012
% https://www.mathworks.com/matlabcentral/answers/46922-correctly-wrap-data-for-spherical-interpolation#answer_57341

function interpolant = generate_scattered_spherical_interpolant( ...
    angles, ...
    values, ...
    interp_method ...
    )

wrap_amount = pi / 4;

az = angles( :, 1 );
az = mod( az, 2 * pi );
az_wrapped_indices = find( ...
    abs( az - pi ) > ( pi - wrap_amount ) ...
    & abs( az - pi ) < pi ...
    );
az_wrapped = ...
    az( az_wrapped_indices ) ...
    - 2 * pi * sign( az( az_wrapped_indices ) - pi );

poles = linspace( 0, 2 * pi, 20 ).';
el = angles( :, 2 );
[ ~, north_pole_el_index ] = max( el );
[ ~, south_pole_el_index ] = min( el );
wrapped_angles = [ poles repmat( [ pi/2 north_pole_el_index ], size( poles ) ) ];
wrapped_angles = [ ...
    wrapped_angles; ...
    poles repmat( [ -pi/2 south_pole_el_index ], size( poles ) ) ...
    ];

all_angles = [ ...
    az el; ...
    az_wrapped el( az_wrapped_indices ); ...
    wrapped_angles( :, 1 : 2 ) ...
    ];
all_angles( :, 1 ) = all_angles( :, 1 ) - pi;
all_indices = [ ...
    ( 1 : size( angles, 1 ) )'; ...
    az_wrapped_indices; ...
    wrapped_angles( :, 3 ) ...
    ];

interpolant = scatteredInterpolant( ...
    all_angles( :, 1 ), ...
    all_angles( :, 2 ), ...
    values( all_indices ), ...
    interp_method ...
    );

end

