function interpolation_methods = objective_interpolation_methods_from_types( types )

types_to_interpolation_methods_map = containers.Map( ...
    { ...
    'categorical', ...
    'continuous' ...
    }, ...
    { ...
    'nearest', ...
    'natural' ...
    } ...
    );
interpolation_methods = types;
for i = 1 : numel( types )
    
    interpolation_methods{ i } = types_to_interpolation_methods_map( types{ i } );
    
end

end

