---
title: "Pareto Frontier Plots"
output: html_notebook
---

Load libraries.

```{r}
library(dplyr)
library(ggplot2)
library(GGally)
library(tikzDevice)
```

Import data.

```{r}
file <- "bearing_block"
data <- read.csv(paste0(file,"_data.txt"))
head(data)
```

Plot pareto frontiers.

```{r}
standardize <- function(x){
  (x-min(x))/(max(x)-min(x))
  }
pairs <-
  data %>%
  select(-phi,-theta) %>%
  mutate_at(.vars = vars(-is_pareto_dominant),
            .funs = funs(standardize)) %>%
  arrange(is_pareto_dominant)
ps <- ggpairs(pairs,
        aes(color = as.factor(is_pareto_dominant),
            fill = as.factor(is_pareto_dominant),
            shape = as.factor(is_pareto_dominant)),
        columns = 2:ncol(pairs),
        columnLabels = vapply(seq(1, ncol(pairs)-1), as.character, c("")),
        upper = list(continuous = "blank"),
        diag = list(continuous = "blankDiag"),
        switch = "both",
        progress = FALSE) +
  #theme_bw() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        aspect.ratio = 1)
for (row in seq_len(ps$nrow)) {
    for (col in seq_len(ps$ncol)) {
        if (row > col) {
          ps[row, col] <- ps[row, col] +
            scale_x_continuous(limits = c(0, 1),
                               breaks = c(0, 1),
                               minor_breaks = seq(from = 0, to = 1, length.out = 11)) +
            scale_y_continuous(limits = c(0, 1),
                               breaks = c(0, 1),
                               minor_breaks = seq(from = 0, to = 1, length.out = 11)) + 
            scale_shape_manual(values = c(3, 21)) +
            scale_color_brewer(palette = "Paired") +
            scale_fill_brewer(palette = "Paired")
        }
    }
}
gpairs_lower <- function(g){
  g$plots <- g$plots[-(1:g$nrow)]
  g$yAxisLabels <- g$yAxisLabels[-1]
  g$nrow <- g$nrow -1

  g$plots <- g$plots[-(seq(g$ncol, length(g$plots), by = g$ncol))]
  g$xAxisLabels <- g$xAxisLabels[-g$ncol]
  g$ncol <- g$ncol - 1

  g
}
ps <- gpairs_lower(ps)
print(ps)
ggsave(paste0(file,"_pareto.png"))
```
