% results_table = base_plate_data;
% figure_resolution_px = 600;
% usrd = UnitSphereResponseData( ...
%     results_table, ...
%     figure_resolution_px ...
%     );
usrp = UnitSphereResponsePlot( usrd, figure_resolution_px );
