function phs = draw_vertical_lines( axhs, x, color, style )

phs = [];
for i = 1 : numel( axhs )
    for j = 1 : numel( x )
        phs( end + 1 ) = line( ...
            axhs( i ), ...
            [ x( j ) x( j ) ], ...
            axhs( i ).YLim, ...
            'color', color, ...
            'linestyle', style ...
            );
    end
end

end

