function [ fdm_mesh, center ] = generate_test_mesh( mold_id, melt_id, shape )

fdm_mesh = mold_id * ones( shape );
center = floor( ( shape - 1 ) / 2 ) + 1;
quarter = floor( ( center - 1 ) / 2 );
melt_ranges = cellfun( ...
    @(x,y) ( x - y ) : ( x + y ), ...
    num2cell( center ), ...
    num2cell( quarter ), ...
    'uniformoutput', false ...
    );
fdm_mesh( melt_ranges{ 1 }, melt_ranges{ 2 }, melt_ranges{ 3 } ) = melt_id;

end

