function data = legacy_run( op )
%% SETUP
data = Results();

%% COMPONENT, MESH
data = run_object( ...
    data, ...
    Component(), ...
    op.input_stl_path ...
    );
data = run_object( ...
    data, ...
    Mesh(), ...
    data.get( Component.NAME ), ...
    op.element_count ...
    );

%% UNDERCUTS
DIMENSION = 3;
data = run_object( ...
    data, ...
    Undercuts(), ...
    data.get( Mesh.NAME ), ...
    DIMENSION ...
    );

%% PARTING PERIMETER, WATERFALL
data = run_object( ...
    data, ...
    PartingPerimeter(), ...
    data.get( Mesh.NAME ), ...
    DIMENSION ...
    );
GRAVITY_DIRECTION = 'down';
data = run_object( ...
    data, ...
    Waterfall(), ...
    data.get( Mesh.NAME ), ...
    data.get( PartingPerimeter.NAME ), ...
    GRAVITY_DIRECTION ...
    );

%% EDT, THIN WALL, BOTTLE CORES
data = run_object( ...
    data, ...
    EdtProfile(), ...
    data.get( Mesh.NAME ) ...
    );
data = run_object( ...
    data, ...
    BottleCores(), ...
    data.get( Mesh.NAME ), ...
    data.get( EdtProfile.NAME ) ...
    );
data = run_object( ...
    data, ...
    CavityThinWall(), ...
    data.get( Component.NAME ), ...
    data.get( Mesh.NAME ), ...
    data.get( EdtProfile.NAME ), ...
    op.thin_wall_cavity_threshold ...
    );
data = run_object( ...
    data, ...
    MoldThinWall(), ...
    data.get( Component.NAME ), ...
    data.get( Mesh.NAME ), ...
    data.get( EdtProfile.NAME ), ...
    op.thin_wall_mold_threshold ...
    );

%% SEGMENTATION, FEEDERS
data = run_object( ...
    data, ...
    Segmentation(), ...
    data.get( EdtProfile.NAME ), ...
    data.get( Mesh.NAME ) ...
    );
data = run_object( ...
    data, ...
    Feeders(), ...
    data.get( Segmentation.NAME ), ...
    data.get( Mesh.NAME ) ...
    );

end
