function [ names, raw_data, runnable ] = run_object( ...
    names, ...
    raw_data, ...
    runnable, ...
    varargin ...
    )

runnable.legacy_run( varargin{ : } );
names{ end + 1 } = runnable.get_storage_name();
raw_data{ end + 1 } = runnable.to_summary();

end

