classdef (Sealed) LinearSystemSolver < SolverBase
    
    methods ( Access = protected )
        function [ x, iteration_count ] = solve_impl( obj, A, b, x0 )
            opts.michol = 'on';
            preconditioner = ichol( A, opts );
            [ x, ~, ~, iteration_count, ~ ] = pcg( ...
                A, ...
                b, ...
                obj.tolerance, ...
                obj.maximum_iteration_count, ...
                preconditioner, ...
                preconditioner.', ...
                x0 ... % empty case handled internally
                );
        end
    end
    
end

