function t_nd = scale_temperatures( t, t_in_range, t_out_range )

if nargin < 3
    t_out_range = [ 0 1 ];
end

t_nd = rescale( ...
    t, ...
    t_out_range( 1 ), ...
    t_out_range( 2 ), ...
    'inputmin', t_in_range( 1 ), ...
    'inputmax', t_in_range( 2 ) ...
    );

end

