sample_geometries_path = what( 'sample_geometries' );
sample_geometries_path = sample_geometries_path.path;

demo( ...
    fullfile( sample_geometries_path, 'bearing_block.stl' ), ...
    fullfile( sample_geometries_path ) ...
    );