function sweep = distance_sweep( ...
    space, ...
    seeds, ...
    sweep_distance_in_voxel_units ...
    )

sweep = bwdistgeodesic( space, seeds );
sweep( isnan( sweep ) | ~space ) = inf;
sweep = sweep < sweep_distance_in_voxel_units;

end