function points = compute_voxel_mesh_points( shape, origin, scale )

points = arrayfun( ...
    @(x,y) x + linspace( 0, scale, y ) .* y, ...
    origin, ...
    shape, ...
    'uniformoutput', false ...
    );

end

