classdef ExternalInterfaces < mesh.utils.Interfaces
    
    methods ( Access = public )
        
        function obj = ExternalInterfaces( ...
                elements, ...
                element_ids, ...
                areas, ...
                distances ...
                )
            
            obj = obj@mesh.utils.Interfaces( ...
                elements, ...
                element_ids, ...
                areas, ...
                distances ...
                );
            
        end
        
    end
    
    
    properties ( Access = protected, Constant )
        
        COLUMN_COUNT = 1;
        
    end
    
end

