function generate_csvs_on_hpc( ...
    stl_path, ...
    option_path, ...
    objective_variables_path, ...
    angles, ...
    slurm_array_job_id, ...
    slurm_job_id, ...
    output_dir ...
    )

opt = OrientationBaseCase( ...
    option_path, ...
    stl_path, ...
    objective_variables_path ...
    );
results = opt.determine_results_as_table( angles );
filename = sprintf( ...
    'results_%s_%i_%i.csv', ...
    opt.get_name(), ...
    slurm_job_id, ...
    slurm_array_job_id );
writetable( results, fullfile( output_dir, filename ) );

end